### ISSUE TITLE
Ruby version confusion

### ISSUE THREAD

**Issue by mctouch** [common-group/services-core#72]
Default build fails due to confusion between ruby versions.

Step 10/13 : RUN bundle install
 ---> Running in abaff78bd51b
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
The git source `git://github.com/catarse/redactor-rails.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/SamMolokanov/fakeweb.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
**Your Ruby version is 2.4.5, but your Gemfile specified 2.4.4**
ERROR: Service 'catarse' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 18

alpine3.7 uses ruby-2.4.5 however the services-core/services/catarse/.ruby-version specifies 2.4.4 as does  the Gemfile.lock

RUBY VERSION
   ruby 2.4.4p296 

The alpine 3.7 repo doesn't even have 2.4.4 as far as I can tell.

dev.Dockerfile - if I change to 2.4.4 it fails
ENV RUBY_PACKAGES ruby=**2.4.4** ruby-io-console ruby-bundler ruby-irb ruby-bigdecimal ruby-json

Executing ca-certificates-20171114-r0.trigger
OK: 389 MiB in 125 packages
ERROR: unsatisfiable constraints:
  ruby-2.4.5-r0:
    breaks: world[ruby=**2.4.4**]
    satisfies: ruby-bundler-1.16.1-r0[ruby]
               ruby-bigdecimal-2.4.5-r0[ruby]
               ruby-irb-2.4.5-r0[ruby]
               ruby-io-console-2.4.5-r0[ruby]
               ruby-json-2.4.5-r0[ruby]
ERROR: Service 'catarse' failed to build: The command '/bin/sh -c apk update &&     apk upgrade &&     apk --update add --virtual build_deps $BUILD_PACKAGES &&     apk --update add $RUBY_PACKAGES' returned a non-zero code: 6

Help :)

**Comment by erickbrenes07** [comment]
I have the same issue, please help.

Thanks.

**Comment by mctouch** [comment]
So I changed the dev.Dockerfile for services/catarse to ruby 2.4.5 and the local bundle to 1.6.2 in the Gemfile.lock and it built ok but then i could not load bundle exec rails console. So I went into the container docker exec -ti services-core_catarse_1 /bin/bash and then apk add ncurses to install the missing infocmp package and the console worked.

However:

I added the required Rails variables

CatarseSettings[:fdw_user] = 'postgres'
CatarseSettings[:common_db_user] = 'postgres'
CatarseSettings[:common_db_port] = '5432'
CatarseSettings[:common_db_password] = 'example'
CatarseSettings[:common_db_name] = 'service_core'

bin/rake db:migrate RAILS_ENV=development fails with 
Caused by:
PG::UndefinedTable: ERROR:  relation "common_schema.subscriptions" does not exist
LINE 4:                            FROM common_schema.subscriptions ...

as noted here https://github.com/catarse/catarse/issues/2890

then as per the comment by adrianob I ran rake common:generate_fdw 

PG::UndefinedObject: ERROR:  role "**postgres**" does not exist
/usr/app/lib/tasks/common.rake:129:in `block (2 levels) in <top (required)>'
Tasks: TOP => common:generate_fdw
(See full trace by running task with --trace)

but it does exist in the service_core database
service_core=# \l
                                  List of databases
     Name     |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
--------------+----------+----------+------------+------------+-----------------------
 postgres     | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 service_core | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
              |          |          |            |            | postgres=CTc/postgres
 template1    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
              |          |          |            |            | postgres=CTc/postgres
(4 rows)

service_core=# \du
                                                       List of roles
     Role name     |                         Attributes                         |                  Member of
-------------------+------------------------------------------------------------+---------------------------------------------
 admin             | Cannot login                                               | {}
 anonymous         | Cannot login                                               | {}
 pg_signal_backend | Cannot login                                               | {}
 platform_user     | Cannot login                                               | {}
 **postgres**          | **Superuser**, Create role, Create DB, Replication, Bypass RLS | {}
 postgrest         |                                                            | {admin,scoped_user,platform_user,anonymous}
 proxy_server      |                                                            | {}
 scoped_user       | Cannot login                                               | {}


this one seems new and not documented as an issue

rake db:seed succeeds

I am stuck with this failure still

Caused by:
PG::UndefinedTable: ERROR:  relation "common_schema.subscriptions" does not exist
LINE 4:                            FROM common_schema.subscriptions ...
                                        ^
/usr/app/db/migrate/20171205150816_use_fdw_tables_on_views.rb:73:in `change'
Tasks: TOP => db:migrate

so my http://hostname:3000 is still asking me to fix the migration 
bin/rake db:migrate RAILS_ENV=development

bin/rake db:migrate RAILS_ENV=test fails
Caused by:
PG::InvalidTextRepresentation: ERROR:  invalid input value for enum payment_service.subscription_status: "canceling"
LINE 9: ..._schema.subscriptions s where status in('active', 'canceling...
                                                             ^
/usr/app/db/migrate/20171221001807_add_canceling_into_user_has_contributed_to.rb:3:in `up'
Tasks: TOP => db:migrate

as does  bin/rake db:migrate RAILS_ENV=production

Any ideas?

Marcus

**Comment by mctouch** [comment]
Hi,

Not yet however I have moved further down the line, not sure whether this is caused by using ruby 2.4.5 instead of what the gem file specified or some other reason. My current issue is that I dont see any data when i "rails db" and go into catarse_db.
Cant find a postgres pg_hba.conf so not too sure how you can only access the db directly , to hopefully give me psql access.

catarse_db-# select * from subscriptions                                                  
catarse_db-# 

yields nothing.

 This is where I am getting so far, I think I need a few things to check before I can solve this one.
Caused by:
PG::InvalidTextRepresentation: ERROR:  invalid input value for enum payment_service.subscription_status: "canceling"
LINE 9: ..._schema.subscriptions s where status in('active', 'canceling...
                                                             ^
/usr/app/db/migrate/20171221001807_add_canceling_into_user_has_contributed_to.rb:3:in `up'

Ill get back to you in a day or so... for an update.

any help would be great on the original version question is it ruby 2.4.5 or 2.4.4 for a successful build run of the catarse docker container not hosted on heroku

**Comment by mctouch** [comment]
Gave up, using Heroku and CircleCI..... Started to build all dependencies based on 2.4.4 on Alpine 3.7 but it was starting to look like a full time job. The heroku build packs take care of the 2.4.4 issue as does the CircleCI integration with Heroku.

**Comment by zahidirfan** [comment]
@devton : any idea how to resolve this?

**Comment by rraallvv** [comment]
Has anyone managed to get this version of Catarse running? I'm new to Docker and I'd like to give it a try. I tried the version without Docker but got stuck on `rake db:migrate` and always get the message about pending migration.

**Comment by tolstenko** [comment]
@rraallvv I am facing the same problem
